### ISSUE TITLE
Log a more descriptive message when running tests without Percy

### ISSUE THREAD

**Issue by wwilsman** [percy/percy-ember#194]
Similar to #186 but rather than silence the logs, we might want to elaborate on them. That issue specifically mentions "for example, if the agent server isn't running" which is the most likely reason for that error. We should state so in the error message.

Current:

```js
`[percy] Error fetching DOM library, disabling: ${err}`
```

Possible suggestion?:

```js
// We know the dom library should be fetchable as long as percy is running.
// Should we still log the error reason? introduce debug logs for the error?
'[percy] Percy is not running - skipping snapshots'
```

Open to other suggestions as well 👂

**Comment by mansona** [comment]
I think you can't be overly verbose on this one 🤔 So you could even put something like this: 

```
[percy] Skipping Percy snapshots - did you forget to run `percy exec`? Check the documentation for more information: https://docs.percy.io/docs/ember
```

Or the alternative is that you can make sure that whatever error message you chose is googlable by making sure that it's written out on https://docs.percy.io/docs/ember. When I was trying to debug this, the very first thing I did was google `[percy] Error fetching DOM library` but I came up with no hits 😞

**Comment by reidab** [comment]
It may be worth mentioning that this error can also occur if you have a content security policy set up that doesn't include `http://localhost:5338` in its `connect-src`.
