### ISSUE TITLE
remove @percy/agent as a dependency

### ISSUE THREAD

**Issue by chrisvdp** [percy/percy-ember#243]
**Problem**

`@percy/agent` is quite a large download. Chromium itself is 130.3 Mb. This download is incurred by everyone who installs `ember-percy`, even though, in our case at least, the Percy agent is only ever invoked in ci. We would prefer to install the Percy agent either globally at each ci run, or as part of our docker container.

**Solution**

Require users of `ember-percy` to also either add `@percy/agent` to their package.json or install it globally. 

**Note**

This may also be a use case for peer dependencies, but it seems that this package does not require specific versions of the Percy agent.

**Comment by wwilsman** [comment]
Hey @chrisvdp!

We actually plan on making this change to all of our SDKs in the next major release (along with other changes such as not automatically downloading Chromium on install). No exact timeline yet, but definitely soon!

We'll leave this issue open until then for others asking the same. 👍

**Comment by chrisvdp** [comment]
Great to hear. Thanks.

**Comment by ctjhoa** [comment]
@wwilsman Can you confirm this is solve with `@percy/ember@3.0.0` and percy-cli config
https://docs.percy.io/docs/skipping-asset-discovery-browser-download ?

**Comment by Robdel12** [comment]
Hey @ctjhoa! That's correct -- I'll go ahead and close this issue out too 💯
