### ISSUE TITLE
Capture scrollTop value for DOM elements

### ISSUE THREAD

**Issue by bttf** [percy/percy-ember#31]
It's possible for multiple elements in an HTML document to have a `scrollTop` attribute set. When Percy creates a DOM snapshot and serializes the HTML, the `scrollTop` position is not included.

Currently we're facing an issue where some of our tests will scroll to different parts of the page, whereupon we want to take a screenshot w/ Percy. Right now these screenshots don't take scroll position into account and end up taking the same screenshot multiple times (default scroll position).

Current workaround is to use the scope argument to force `percySnapshot` to focus on a particular section. Would love if Percy could take `scrollTop` into account and depict scroll position in its snapshots

**Comment by djones** [comment]
Related: https://github.com/percy/percy-cypress/issues/2
