### ISSUE TITLE
Recent `@percy/sdk-utils` change breaks AMD import

### ISSUE THREAD

**Issue by dfreeman** [percy/percy-ember#610]
## The problem

Starting 2 days ago, our nightly "forget the lockfile and see what happens" compatibility tests for our design system package started failing due to test loader errors. I've tracked it down to `@percy/ember` failing to load `@percy/sdk-utils` due to the change that landed in https://github.com/percy/cli/pull/1000

<img width="404" alt="the Chrome debugger paused while attempting to call the string '@percy/sdk-utils' as a function" src="https://user-images.githubusercontent.com/108688/181524398-e5941dcc-3dcc-4d26-b474-a117b7cf0326.png">

## Environment

- Node version: 16.15.0
- `@percy/cli` version: 1.6.4

## Code to reproduce issue

This should be reproducible in this repo by refreshing the `@percy/sdk-utils` entry in the lockfile here.

**Comment by wwilsman** [comment]
Hey @dfreeman!

Can you give v3.0.1 a try? 🤞

**Comment by dfreeman** [comment]
That looks like it did the trick—thank you for the quick fix!
