### ISSUE TITLE
Shadow DOM support for Ember

### ISSUE THREAD

**Issue by itsjwala** [percy/percy-ember#705]
### Discussed in https://github.com/percy/percy-ember/discussions/704

<div type='discussions-op-text'>

<sup>Originally posted by **c69-addepar** January 25, 2023</sup>
Hi Team, @itsjwala ,

since `1.19.0-alpha.0`, `@percy/cli` now supports Shadow DOM. 

Unfortunately, the changes in that repo alone are not enough to enable support for Ember apps. See https://github.com/percy/cli/pull/1165#issuecomment-1403956686

Happy to provide more details if needed.

CC: @mmun @aschenoni 

</div>

**Comment by c69-addepar** [comment]
Thank you so much @itsjwala ! We have confirmed that `@percy/cli 1.19.2` + `@percy/ember 4.0.2` work well with our code.

This allowed us to remove the fork of 1.0.3, and switch back to mainline Percy! 🎉
