### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by amiarSlimane** [percy/percy-ember#736]
I run ember tests with Percy , before it was working, recently the build always fail with no error showing,  
![scrnn](https://user-images.githubusercontent.com/24839094/234217701-7eeabe6c-6b2f-4096-a3ac-f87da2ff89da.png)

on the platform i get this message 
![image](https://user-images.githubusercontent.com/24839094/234218048-dddadc6a-4fdb-474b-95ba-132a7fe8544e.png)

it is working when using `percy snapshot snapshots.json` but in my case i need to use `percySnapshot`  during Ember tests,

i am using : 

- ember: 3.24
- node: 14
- @percy/cli": 1.24.0
- @percy/ember: 4.2.0

thank you.

**Comment by itsjwala** [comment]
hey @amiarSlimane we'll require more details here, please reach out to us via http://browserstack.com/support
